version: "3.8"
services:
    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - '3000:3000'
        volumes: 
            - ./frontend:/frontend
            - /frontend/node_modules